#! /usr/bin/bash

# lancement test par defaut
px17 $1

# lancement test stoplist
px17 $1 -s le_dormeur_du_val.txt stoplist

# lancement test golist 
px17 $1 -s le_dormeur_du_val.txt stoplist


#TEST SUR TEXTE LONG
# lancement test stoplist
px17 $1 -s le_horla.txt stoplist

# lancement test golist 
px17 $1 -g le_horla.txt stoplist

#TEST SUR PAGE HTML
# lancement test stoplist
px17 $1 -s programmation.html balisesHtml

# lancement test golist 
px17 $1 -g programmation.html balisesHtml





    