all : cx25.0 cx25.1 cx25.2

cx25.0 : cx25.0.c
	gcc -Wall -g -std=gnu99  cx25.0.c -o cx25.0

cx25.1 : cx25.1.c
	gcc -Wall -g -std=gnu99  cx25.1.c -o cx25.1

cx25.2 : cx25.2.c
	gcc -Wall -g -std=gnu99  cx25.2.c -o cx25.2