#! /bin/tcsh

#cx17 : test de regression
#$1 = minor.bugfix update number
gcc -Wall cx17.$1.c -o cx17.$1

# validation de la compilation
if ($? != 0) exit

# lancement du test
cx17.$1 indexe-moi.texte > cx17.$1.test
